export default {
  SIGN_IN_REQUEST: '@auth/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: '@auth/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: '@auth/SIGN_IN_FAILURE',
  SIGN_OUT_REQUEST: '@auth/SIGN_OUT_REQUEST',
  UPDATE_PROFILE_SUCCESS: '@auth/UPDATE_PROFILE_SUCCESS',
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
};
